openapi: 3.0.1
info:
  title: testFile
  description: API Definition of testFile
  version: 1.0.0
servers:
- url: http://localhost:8290/testfile
paths:
  /:
    get:
      responses:
        default:
          description: Default response
