openapi: 3.0.1
info:
  title: fileSplitAPI
  description: API Definition of fileSplitAPI
  version: 1.0.0
servers:
- url: http://localhost:8290/file
paths:
  /split:
    get:
      responses:
        default:
          description: Default response
